services:
  - type: web
    name: task-flow
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    pullRequestPreviewsEnabled: false
